### ISSUE TITLE
failed to create the java virtual machine

### ISSUE THREAD

**Issue by mtxmks** [subgraph/Vega#86] opened 2013-08-02 03:07 UTC
please
The following error occurs when trying to start VEGA

My OS is W7 86x

some solution?

http://i.imgur.com/haHI9oh.png

**Comment by dma** [comment] 2013-08-08 22:11
Yes. The problem is that the max heap size for the Oracle JVM on 32-bit Windows seems to be ~1.5GB. In build 97 we increased the max heap size to 2GB for all platforms - this introduced the error.

The solution is to edit the Vega.ini file in the Vega directory. In the file, change the following:

-Xmx2048m

To:

-Xmx1536m (if that doesn't work, try -Xmx1024m).

Save it, then restart Vega.

Let me know if this works for you. We'll be releasing a build shortly that eliminates this issue.

**Comment by dma** [comment] 2013-08-11 13:57
Fixed in build 108, which is available for download at http://www.subgraph.com.

**Closed as completed by dma** 2013-08-11 13:57 UTC

**Comment by emiles002** [comment] 2015-02-24 16:15
Running on OpenSuse 13.1, JVM 1.7.0_55.  Made the -Xmx1024m change in Vega.ini.  JVM crashes ...

No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 2401Mhz, 15768MB
[000:000] Computer model: Not available
[000:000] Browser XEmbed support present: 1
[000:000] Browser toolkit is Gtk2.
[000:000] Using Gtk2 toolkit
No bp log location saved, using default.
[000:000] Cpu: 6.60.3, x8, 2401Mhz, 15768MB
[000:000] Computer model: Not available
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.8) (suse-24.17.1-x86_64)
OpenJDK 64-Bit Server VM (build 24.55-b03, mixed mode)
#

# A fatal error has been detected by the Java Runtime Environment:

#

# SIGSEGV (0xb) at pc=0x00007f80143786b8, pid=6451, tid=140188674823936

#

# JRE version: OpenJDK Runtime Environment (7.0_55-b14) (build 1.7.0_55-b14)

# Java VM: OpenJDK 64-Bit Server VM (24.55-b03 mixed mode linux-amd64 compressed oops)

# Problematic frame:

# C  [libgobject-2.0.so.0+0x1a6b8]  g_object_get_qdata+0x18

#

# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

#

# An error report file with more information is saved as:

# /tmp/jvm-6451/hs_error.log

#

# If you would like to submit a bug report, please include

# instructions on how to reproduce the bug and visit:

# http://icedtea.classpath.org/bugzilla

# The crash happened outside the Java Virtual Machine in native code.

# See problematic frame for where to report the bug.

#

**Comment by emiles002** [comment] 2015-02-24 16:16
sorry about the XL font, I just did a cut/paste from a terminal window.
