### ISSUE TITLE
No way to export the scan results

### ISSUE THREAD

**Issue by sudhaharv** [subgraph/Vega#103] opened 2013-10-17 10:08 UTC
Once the scanning is done, we need to raise bugs. for that we have to export the test results.

we could not find any options to export the scan results

**Comment by iBringsTheRuckus** [comment] 2013-11-20 07:46
Would be great to import too.

**Comment by ouaziz** [comment] 2013-12-07 21:34
i need to export results, how can i do ?????

**Comment by dma** [comment] 2014-07-25 15:24
Closing, duplicate of #13. We will implement this (and possibly importing).

**Closed as completed by dma** 2014-07-25 15:24 UTC

**Comment by rdhnsop** [comment] 2014-09-10 16:09
Is there an ETA on when we will be able to export results?
